### ISSUE TITLE
Stage Editor not working.

### ISSUE THREAD

**Issue by EvcazinDeveloper** [jamuelthegamer/FNF-Psych-Engine-Plus#2]
### Describe your problem here.

**Stage Editor.**

As you know, the Stage Editor is an feature on PsychEngine+,  where you can edit Stages. But...

**Bug**

The variables are not working, that makes the stage not work well. I mean, the position is 0, 0, setScrollFactor variables is , , so it wont work.

But how do i fix this?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i only use LUA as coding as my Visual Studio 2019 Community don't help.

**Comment by jamuelthegamer** [comment]
Well,The stage editor has lots reported issues I will make a new stage editor in 1.2 Update
