### ISSUE TITLE
Here are all of The Bugs I could Find in 1.2.0 Version of Psych Engine+

### ISSUE THREAD

**Issue by obscuryth** [jamuelthegamer/FNF-Psych-Engine-Plus#3]
### Describe your bug here.

- Small Lagspikes during Gameplay
- The Game Crashes at the End of Song 1 in Week 2
- The Game Crashes at the End of Song 2 in Week 3
- The Game Crashes at the End of Song 1 in Week 4
- The Game Crashes almos at the End of Song 1 (around 0:19) in Week 5
- The Game Crashes at the End of Song 1 in Week 6
- The Game Crashes in the Middle of Song 1 in Week 7
- The Game has some Small Lag Spikes during Gameplay

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I didn't Edit anything. It's just The Base Engine.

**Comment by jamuelthegamer** [comment]
I'll fix in 1.2.1 Coming Soon
